name: test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test_linux:
    name: "linux test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: build
        run: |
          docker buildx build . --platform linux/amd64,linux/arm64,linux/arm/v7
  test_windows:
    runs-on: windows-latest
    name: "windows build: ${{ matrix.arch }}"
    strategy:
      fail-fast: true
      matrix:
        arch: [x64]
    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: |
          cmake -Bbuild -DCMAKE_INSTALL_PREFIX=_install/piper-phonemize
      - name: build
        run: |
          cmake --build build --config Release
      - name: install
        run: |
          cmake --install build
      - name: check
        run: |
          _install/piper-phonemize/bin/piper_phonemize_exe --help
  test_mac:
    name: "mac test: ${{ matrix.arch }}"
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        arch: [x64, aarch64]
    steps:
      - uses: actions/checkout@v3
      - name: configure
        run: |
          cmake -Bbuild -DCMAKE_INSTALL_PREFIX=_install/piper-phonemize
      - name: build
        run: |
          cmake --build build --config Release
      - name: install
        run: |
          cmake --install build
      - name: test
        run: |
          DYLD_LIBRARY_PATH=$PWD/_install/piper-phonemize/lib _install/piper-phonemize/bin/piper_phonemize --help
